### ISSUE TITLE
Adjust Circulating Supply and extend Coins API

### ISSUE THREAD

**Issue by Endogen** [idena-network/idena-indexer#1]
Circulating Supply is very important for a lot of investors and it is generally defined like this:

**Binance**
> The term circulating supply refers to the number of cryptocurrency coins or tokens that are **publicly available** and circulating in the market.

**CoinMarketCap**
> Circulating Supply is the best approximation of the number of coins that are circulating in the market and in the **general public's hands**.

IDENA doesn't have a locking mechanism so technically the Circ. Supply that can be retrieved here https://api.idena.io/api/CirculatingSupply might be right but based on the previously mentioned definitions it's not accurate.

Since not the whole amount of DNA mentioned in the CirculatingSupply API is publicly available, i would propose to correct the amount and add more detailed data (total premine and its partition into the different allocations) to the Coins API https://api.idena.io/api/Coins.

**Comment by midenaio** [comment]
Is it a [duplicate issue](https://github.com/idena-network/idena-indexer/issues/2)? It should have been fixed already

**Comment by Endogen** [comment]
This can be closed now yes
