### ISSUE TITLE
Numbers don't add up

### ISSUE THREAD

**Issue by idenatoday** [idena-network/idena-indexer#2]
https://scan.idena.io/circulation
and API is not consistent and not right.

- some wallets in locked list are not locked and sent significant amounts, these are not vested coins.
- total sum of the listed wallets balances does not exactly fit the vested amount shown above
- circulating supply, whose tooltip says total - vested - staked is in fact total - vested.

The whole thing is not consistent, we're not able to get a clear picture of the coin metrics.

**Comment by mbidenaio** [comment]
Fixed. Thank you.
